[toolchain]

[features]
resolution = true
skip-lint = false

[programs.mainnet]
dlan_stake = "3hQsDEYknZmKKUBApAGtcGPy395ogJdiB8DCvMKh24K7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/dlan_stake"]

